
POST http://0.0.0.0:9000/feeder/feed
Content-Type: application/json

{
    "commands": [
      {
        "id": {
          "value": "A"
        },
        "name": "setup-iris",
        "params": []
      },
      {
        "id": {
          "value": "B"
        },
        "name": "setup-iris",
        "params": []
      }
    ]
}

###

GET ws://0.0.0.0:9000/Streaming2/from

###`
#Content-Type: application/json
